
import Head from 'next/head'
import Image from 'next/image'
import Card from '../components/Card'
import SearchC from '../components/Search'
import styles from '../styles/Home.module.css'
import {useState} from 'react'
import {BiSearch} from 'react-icons/bi'
import axios from 'axios'


export default function Home() {
    const [city,setCity]=useState('')
  const[weather,setWeather]=useState({})
  const url=`https://api.openweathermap.org/data/2.5/weather?q=${city}&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}&units=metric`
  
  const callData=(e)=>{
     e.preventDefault()
     axios.get(url).then((response)=>{
      setWeather(response.data)
     }),
     setCity('')
  }
  return (
    <div className=''>
      <Head>
        <title>Aimsir agus Snamh App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image src='https://images.unsplash.com/photo-1535479804851-93f60320e644?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTl8fHRoZSUyMGJ1cnJlbnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60' 
      layout='fill'
      className='object-fit'
      alt='/'
      />
      <div className='absolute h-full top-0 bottom-0 left-0 right-0 bg-black/50 z-[1]'/>

      <div className='z-30 absolute flex items-center justify-between ml-[100px]  lg:ml-[500px] top-[50px] bg-transparent border-white border-2 p-2 rounded-2xl w-[280px] lg:w-[400px] '>
        <input 
        value={city}
        className='border-black focus:outline-none  bg-transparent text-white' 
        placeholder='Enter City'
        onChange={(e)=>setCity(e.target.value)}
        />
        <button
      onClick={(e)=>callData(e)}
       className=' p-2 relative'>
        <BiSearch size={20} className='text-white'/>
       </button>
      </div>
      <div className='absolute top-[100px] w-[200px] lg:w-[800px] h-[400px] p-5 '>
      {weather.main && <Card data={weather}/>}
      </div>
   
    </div>
  )
}

